version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: scraping_service
      RABBITMQ_DEFAULT_PASS: your_secure_password
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/usr/src/app
    command: npm run dev
    environment:
      - DATABASE_URL=postgresql://brujula_test_db_owner:EVAIZ5hTRd1K@ep-floral-hall-a56zspl1.us-east-2.aws.neon.tech/brujula_test_db?sslmode=require
      - JWT_SECRET=SECRET_KEY
      - RABBITMQ_URL=amqp://scraping_service:your_secure_password@rabbitmq:5672/
    networks:
      - app-network


  backend-flask:
    build:
      context: ./backend-scraper
      dockerfile: Dockerfile
    container_name: backend-scraper
    ports:
      - "5000:5000"
    volumes:
      - ./backend-scraper:/app
    depends_on:
      - rabbitmq
      - celery-worker
    environment:
    - RABBITMQ_URL=amqp://scraping_service:your_secure_password@rabbitmq:5672
    - RABBITMQ_QUEUE=comentarios_scraping_queue
    - RABBITMQ_USER=scraping_service
    - RABBITMQ_PASSWORD=your_secure_password
    - RABBITMQ_HOST=rabbitmq
    - RABBITMQ_PORT=5672
    - DATABASE_URL=postgresql://brujula_test_db_owner:EVAIZ5hTRd1K@ep-floral-hall-a56zspl1.us-east-2.aws.neon.tech/brujula_test_db?sslmode=require
    - JWT_SECRET=SECRET_KEY
    - SERVICE_EMAIL=usuario3.test@test.com
    - SERVICE_PASSWORD=password123
    - CELERY_BROKER_URL=amqp://scraping_service:your_secure_password@rabbitmq:5672
    - CELERY_RESULT_BACKEND=rpc://
    networks:
      - app-network


  celery-worker:
    build:
      context: ./backend-scraper
      dockerfile: Dockerfile
    container_name: celery-worker
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_URL=amqp://scraping_service:your_secure_password@rabbitmq:5672
      - RABBITMQ_QUEUE=comentarios_scraping_queue
      - RABBITMQ_USER=scraping_service
      - RABBITMQ_PASSWORD=your_secure_password
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - DATABASE_URL=postgresql://brujula_test_db_owner:EVAIZ5hTRd1K@ep-floral-hall-a56zspl1.us-east-2.aws.neon.tech/brujula_test_db?sslmode=require
      - JWT_SECRET=SECRET_KEY
      - CELERY_BROKER_URL=amqp://scraping_service:your_secure_password@rabbitmq:5672
      - CELERY_RESULT_BACKEND=rpc://
    command: celery -A app.celery worker --loglevel=info
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/app_modules
    depends_on:
      - backend
    command: npm start
    environment:
      - REACT_APP_BACKEND_URL=http://backend:4000
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
